-- Consulta #1 --
CREATE FUNCTION ClientePedido(idpedidoEntrada integer)
RETURNS TABLE (nombreCliente varchar, nombrepedido varchar) AS 
$$
	SELECT VD.NOMBRECLIENTE, PF.NOMBRE
	FROM VENTASDATOS VD
	INNER JOIN VENTAS V ON VD.IDVENTASDATOS = V.IDVENTASDATOS
	INNER JOIN PRODUCTOFINAL PF ON V.IDPRODUCTOFINAL = PF.IDPRODUCTOFINAL
	WHERE VD.IDVENTASDATOS = idpedidoEntrada;
$$ LANGUAGE SQL;
SELECT CLIENTEPEDIDO(14);

-- Consulta #2 --
CREATE VIEW VistaEmpleadosEdad AS
SELECT *
FROM empleados
WHERE EXTRACT(YEAR FROM AGE(CURRENT_DATE, fechanacimiento)) BETWEEN 20 AND 30;
SELECT * FROM vistaEmpleadosEdad;

-- Consulta #3 --
SELECT E.NOMBRE AS nombreEmpleado, VD.*, PF.NOMBRE AS nombreProductoFinal
FROM EMPLEADOS E
INNER JOIN VENTASDATOS VD ON E.IDEMPLEADO = VD.IDEMPLEADO
INNER JOIN VENTAS V ON VD.IDVENTASDATOS = V.IDVENTASDATOS
INNER JOIN PRODUCTOFINAL PF ON V.IDPRODUCTOFINAL = PF.IDPRODUCTOFINAL;

-- Consulta #4 --
CREATE FUNCTION ObtenerProductoProveedor(nombreProveedor varchar)
RETURNS TABLE (nombreProveedor varchar, productoQueProvee varchar, idProductobasico integer) AS 
$$
SELECT P.NOMBREPARTICULAR, PB.NOMBRE AS productoQueProvee, PB.IDPRODUCTOBASICO
FROM PROVEEDOR P
INNER JOIN PRODUCTOBASICO PB ON P.TELEFONO = PB.TELEFONO
WHERE P.NOMBREPARTICULAR = nombreProveedor;
$$ LANGUAGE SQL;
SELECT * FROM OBTENERPRODUCTOPROVEEDOR('La piedra');

-- Consulta #5 --
SELECT p.TELEFONO AS TELEFONO_PROVEEDOR, p.NOMBREPARTICULAR AS NOMBRE_PROVEEDOR,
AVG(pr.EXISTENCIA * pr.PRECIOPORKG) AS PROMEDIO_VENTA FROM PROVEEDOR p
JOIN PRODUCTOBASICO pr ON p.TELEFONO = pr.TELEFONO
JOIN PRODUCTOSREQUERIDOS prr ON pr.IDPRODUCTOBASICO = prr.IDPRODUCTOBASICO
GROUP BY p.TELEFONO, p.NOMBREPARTICULAR ORDER BY PROMEDIO_VENTA DESC;

-- Consulta #6 --
CREATE VIEW CANTIDAD_PEDIDOS_POR_FECHA AS
SELECT FECHAVENTA, COUNT(*) AS CANTIDAD_PEDIDOS
FROM VENTASDATOS vd
JOIN VENTAS v ON vd.IDVENTASDATOS = v.IDVENTASDATOS
GROUP BY FECHAVENTA;
SELECT * FROM CANTIDAD_PEDIDOS_POR_FECHA

-- Consulta #7 --
INSERT INTO PRODUCTOFINAL (NOMBRE)
VALUES
  ('Pizza Especial'),
  ('Pizza Nueva York'),
  ('Pizza Chicago'),
  ('Pizza Nutella'),
  ('Pizza Arabe'),
  ('Pizza XXL'),
  ('Pizza Italiana'),
  ('Pizza de Pollo'),
  ('Pizza con Tocino'),
  ('Pizza Oriental');
SELECT * FROM PRODUCTOFINAL

INSERT INTO PROVEEDOR (TELEFONO, NOMBREPARTICULAR, CALLE, COLONIA, DELEGACIONMUNICIPIO, CP, PAIS, TIPO)
VALUES
  ('5508805696', 'SuKarne', 'Erlenmeyer', 'Centro', 'Tlalnepantla', 57890, 'España', 0),
  ('5574359054', 'Alpura', 'Merlina', 'Residencial', 'Nezayork', 50068, 'Alemania', 0),
  ('5512491956', 'GotenPi', 'Mazaryk', 'Toloaya', 'Naucalpunk', 01289, 'Australia', 1);
SELECT * FROM PROVEEDOR

WITH pedidos AS (
  INSERT INTO VENTASDATOS (NOMBRECLIENTE, FECHAVENTA, IDEMPLEADO)
  VALUES
    ('Encarnación', '2023-06-26', 1),
    ('Verónica', '2023-06-25', 2),
    ('Monserrat', '2023-06-27', 3),
    ('Enrique', '2023-06-24', 4)
  RETURNING IDVENTASDATOS
)
INSERT INTO VENTAS (IDPRODUCTOFINAL, IDVENTASDATOS)
SELECT
  (SELECT IDPRODUCTOFINAL FROM PRODUCTOFINAL ORDER BY RANDOM() LIMIT 1),
  IDVENTASDATOS
FROM pedidos;
SELECT * FROM VENTASDATOS

WITH clientes AS (
  INSERT INTO VENTASDATOS (NOMBRECLIENTE, FECHAVENTA, IDEMPLEADO)
  VALUES
    ('Sakum', '2023-06-23', 5),
    ('Popriko', '2023-06-13', 6)
  RETURNING IDVENTASDATOS
)
INSERT INTO VENTAS (IDPRODUCTOFINAL, IDVENTASDATOS)
SELECT
  (SELECT IDPRODUCTOFINAL FROM PRODUCTOFINAL ORDER BY RANDOM() LIMIT 1),
  IDVENTASDATOS
FROM clientes;
SELECT * FROM VENTASDATOS

-- Consulta #8 --
CREATE VIEW REPORTE_PEDIDOS AS
SELECT
    vd.NOMBRECLIENTE AS Cliente,
    STRING_AGG(CAST(vd.IDVENTASDATOS AS VARCHAR), ', ') AS Pedidos,
    STRING_AGG(pf.NOMBRE, ', ') AS Productos,
    COUNT(*) AS CantidadPedidos,
    SUM(pb.PRECIOPORKG * pr.CANTIDADREQUERIDA / 25) AS "Precio Total",
    CASE
        WHEN COUNT(*) BETWEEN 1 AND 3 THEN 'Cliente Ocasional'
        WHEN COUNT(*) BETWEEN 4 AND 10 THEN 'Cliente Casual'
        ELSE 'Cliente Frecuente'
    END AS Leyenda
FROM
    VENTASDATOS vd
    JOIN VENTAS v ON vd.IDVENTASDATOS = v.IDVENTASDATOS
    JOIN PRODUCTOFINAL pf ON v.IDPRODUCTOFINAL = pf.IDPRODUCTOFINAL
    JOIN PRODUCTOSREQUERIDOS pr ON pf.IDPRODUCTOFINAL = pr.IDPRODUCTOFINAL
    JOIN PRODUCTOBASICO pb ON pr.IDPRODUCTOBASICO = pb.IDPRODUCTOBASICO
GROUP BY
    vd.NOMBRECLIENTE;
SELECT * FROM REPORTE_PEDIDOS