CREATE TABLE EMPLEADOS(
	IDEMPLEADO SERIAL NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	APELLIDOPATERNO VARCHAR(20) NOT NULL,
	APELLIDOMATERNO VARCHAR(20) NOT NULL,
	FECHANACIMIENTO DATE NOT NULL,
	DIRECCIONCALLE VARCHAR(20) NOT NULL,
	NUMEXTERIOR INTEGER NULL,
	NUMINTERIOR INTEGER NULL,
	COLONIA VARCHAR(30) NOT NULL,
	DELEGACIONMUNICIPIO VARCHAR(30) NOT NULL,
	CP INTEGER NOT NULL,
	CONSTRAINT PKEMPLEADO PRIMARY KEY (IDEMPLEADO)
);

CREATE TABLE VENTASDATOS(
	IDVENTASDATOS SERIAL NOT NULL,
	NOMBRECLIENTE VARCHAR(20) NOT NULL,
	FECHAVENTA DATE NOT NULL,
	IDEMPLEADO INTEGER NOT NULL,
	CONSTRAINT PKVENTASDATOS PRIMARY KEY (IDVENTASDATOS),
	CONSTRAINT FKVENTASDATOS FOREIGN KEY (IDEMPLEADO) REFERENCES EMPLEADOS (IDEMPLEADO)
);

CREATE TABLE PRODUCTOFINAL(
	IDPRODUCTOFINAL SERIAL NOT NULL,
	NOMBRE VARCHAR(20) NULL,
	CONSTRAINT PKPRODUCTOFINAL PRIMARY KEY (IDPRODUCTOFINAL)
);

CREATE TABLE VENTAS(
	IDPRODUCTOFINAL INTEGER NOT NULL,
	IDVENTASDATOS INTEGER NOT NULL,
	CONSTRAINT FKVENTASPRODUCTOFINAL FOREIGN KEY (IDPRODUCTOFINAL) REFERENCES PRODUCTOFINAL (IDPRODUCTOFINAL),
	CONSTRAINT FKVENTASVENTASDATOS FOREIGN KEY (IDVENTASDATOS) REFERENCES VENTASDATOS (IDVENTASDATOS)
);

CREATE TABLE PROVEEDOR(
	TELEFONO VARCHAR(10) NOT NULL,
	NOMBREPARTICULAR VARCHAR(100) NOT NULL,
	CALLE VARCHAR(20) NOT NULL,
	NUMEXTERIOR INTEGER NULL,
	COLONIA VARCHAR(30) NOT NULL,
	DELEGACIONMUNICIPIO VARCHAR(30) NOT NULL,
	CP INTEGER NOT NULL,
	ESTADO VARCHAR(20) NULL,
	PAIS VARCHAR(20) NOT NULL,
	TIPO INTEGER NOT NULL,
	CONSTRAINT PKPROVEEDOR PRIMARY KEY (TELEFONO)
);

CREATE TABLE PRODUCTOBASICO(
	IDPRODUCTOBASICO SERIAL NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL,
	EXISTENCIA INTEGER NOT NULL,
	PRECIOPORKG INTEGER NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	CONSTRAINT PKPRODUCTOBASICO PRIMARY KEY (IDPRODUCTOBASICO),
	CONSTRAINT FKPRODUCTOBASICO FOREIGN KEY (TELEFONO) REFERENCES PROVEEDOR (TELEFONO)
);

CREATE TABLE PRODUCTOSREQUERIDOS(
	IDPRODUCTOFINAL INTEGER NOT NULL,
	CANTIDADREQUERIDA INTEGER NOT NULL,
	IDPRODUCTOBASICO INTEGER NOT NULL,
	CONSTRAINT FKPRODUCTOSREQUERIDOSPRODUCTOFINAL FOREIGN KEY (IDPRODUCTOFINAL) REFERENCES PRODUCTOFINAL (IDPRODUCTOFINAL),
	CONSTRAINT FKPRODUCTOSREQUERIDOSPRODUCTOBASICO FOREIGN KEY (IDPRODUCTOBASICO) REFERENCES PRODUCTOBASICO (IDPRODUCTOBASICO)
);
